version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly